name: untitled1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  firebase_storage: ^11.7.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.10
  provider: ^6.1.2
  flutter_chat_bubble: ^2.0.2
  modal_progress_hud_nsn: ^0.5.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background/background1.jpg
    - assets/background/background2.jpg
    - assets/background/background3.jpg
    - assets/character/character1.png
    - assets/character/character2.png
    - assets/character/character3.png
    - assets/images/123.jpg
    - assets/images/111.png
    - assets/images/red.jpg
    - assets/images/back_icon.png
    - assets/images/image_69.png
    - assets/images/image_101.png
    - assets/images/image_102.png
    - assets/images/image_103.png
    - assets/images/image_104.png
    - assets/images/image_105.png
    - assets/images/image_106.png
    - assets/images/image_107.png
    - assets/images/image_108.png
    - assets/images/image_109.png
    - assets/images/image_110.png
    - assets/images/image_111.png
    - assets/images/image_112.png
    - assets/images/image_114.png
    - assets/images/shop_logo.png
    - assets/character/
    - assets/background/
    - assets/red.jpg
    - assets/coming_soon.png
    - assets/images/login_back.png
    - assets/images/arrow.png
    - assets/images/google.png

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
    - family: continuous
      fonts:
        - asset: assets/fonts/continuous.ttf
