// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6Fkga57MjWBwJQiBKhtyreGsZbkzxbc',
    appId: '1:90392379993:web:6bdb9583777d72f5286748',
    messagingSenderId: '90392379993',
    projectId: 'project-92f40',
    authDomain: 'project-92f40.firebaseapp.com',
    storageBucket: 'project-92f40.appspot.com',
    measurementId: 'G-LR04XTY5VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDte_AKJlAEZld3aU7mcCGg856nFxhk0',
    appId: '1:90392379993:android:93f162833978fc54286748',
    messagingSenderId: '90392379993',
    projectId: 'project-92f40',
    storageBucket: 'project-92f40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD-prxcicw1Hs6MAaNu0154pPsCH4akLw',
    appId: '1:90392379993:ios:aa3a3bb353450b62286748',
    messagingSenderId: '90392379993',
    projectId: 'project-92f40',
    storageBucket: 'project-92f40.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD-prxcicw1Hs6MAaNu0154pPsCH4akLw',
    appId: '1:90392379993:ios:12395278df4ff55e286748',
    messagingSenderId: '90392379993',
    projectId: 'project-92f40',
    storageBucket: 'project-92f40.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
